### ISSUE TITLE
invalid value for argument address:

### ISSUE THREAD

**Issue by MSalim7** [Druvis-Timma/Mikrotik#4] opened 2023-01-30 12:21 UTC
[I have tried different variations of commands but to no avail.](https://disk.yandex.ru/i/94br14zJTqmttA)
I have the latest firmware 7.8 beta installed.

```
while resolving ip: name does not exist
while resolving ip6: name does not exist
```

**Comment by Druvis-Timma** [comment] 2023-01-30 16:37
Interesting, not sure what is causing that, but  the issue is with your router. Do the commands work when typed in the terminal?

**Comment by atilla-israel** [comment] 2023-01-30 17:21
with user and password configured does not send commands. 
If writing script with user without password works normally.

`failure: authentication failure
[aaaaaa@RB5009] /system/script> 
14:15:55 echo: system,error,critical login failure for user aaaaaa from 127.0.0.1 via ssh
[aaaaaa@RB5009] /system/script>`

**Comment by MSalim7** [comment] 2023-01-31 07:19
>Interesting, not sure what is causing that, but the issue is with your router. Do the commands work when typed in the terminal?

Yes. [Let me demonstrate.](https://disk.yandex.ru/i/iCNGQ3-BBbMxeA)

**Comment by Druvis-Timma** [comment] 2023-03-06 09:33
Not sure what has gone wrong there, but the router is failing to resolve an IP. That cannot be fixed within this script.

**Closed as completed by Druvis-Timma** 2023-03-06 09:33 UTC
